### ISSUE TITLE
Replacing can be quite invasive

### ISSUE THREAD

**Issue by kLabz** [Jibbarth/Github-Other-bugtracker#5]
I was leaving a comment on a PR about css, and I couldn't talk about the color [#000](https://redmine.example.com/issues/000), even in code blocks.
It would be great to allow disabling the auto-replace for the current textarea.

**Comment by Jibbarth** [comment]
Great idea ! Thanks man, i'll do it.

**Comment by kLabz** [comment]
Up, this is really annoying (didn't know I still had this extension installed on this computer Oo)

**Comment by Jibbarth** [comment]
I put this at the top of my priorities :sweat_smile: 

Or if you have some time, feel free to submit a PR :wink:

**Comment by Jibbarth** [comment]
Done :wink: It's not wonderfull (just a checkbox, disabled by default), but it does the job.
